# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Erik Pettersson
tagline:             'Mina tankar (tekniska analyser) kring löpning'
description:         'En blogg om min träning inför Stockholm Marathon'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Custom vars
disqus_shortname: erik-lars-johan
